### PR TITLE
Replace env vars instead of updating them in IDEA

### LINKED ISSUE #53: [Bug] Plugin conflict with IDEA ScalaTest
If I create ScalaTest Run/Debug Configuration and enable EnvFile something went wrong. When I'm trying to run this configuration i've got error:
```
Error running 'IT-tests':
Unknown error
```

If I restart IDE - error disappears. If I change something in 'IT-tests' configuration - it appears again and Configuration Environment variables fills with .env file content (it didn't happen before as I remember)

**IDE**
IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 25, 2017

JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2
 
**idea.log**
```log
2018-01-12 10:08:47,515 [ 316559]   INFO - s.CompilerReferenceServiceImpl - backward reference index reader is opened 
2018-01-12 10:08:47,653 [ 316697]   WARN - xecution.runners.ExecutionUtil - Execution error without description 
java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.clear(ImmutableMap.java:620)
	at net.ashald.envfile.platform.ui.EnvFileConfigurationEditor.patchEnvironmentVariables(EnvFileConfigurationEditor.java:122)
	at net.ashald.envfile.products.idea.IdeaRunConfigurationExtension.updateJavaParameters(IdeaRunConfigurationExtension.java:53)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration$$anon$2.$anonfun$createJavaParameters$8(AbstractTestRunConfiguration.scala:442)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration$$anon$2.$anonfun$createJavaParameters$8$adapted(AbstractTestRunConfiguration.scala:441)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration$$anon$2.createJavaParameters(AbstractTestRunConfiguration.scala:441)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:33)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:90)
	at com.intellij.execution.runners.GenericProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:75)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-01-12 10:08:48,245 [ 317289]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /Applications/IntelliJ IDEA.app/Contents/lib/jps-launcher.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/tools.jar:/Applications/IntelliJ IDEA.app/Contents/lib/optimizedFileManager.jar 
2018-01-12 10:08:48,306 [ 317350]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
2018-01-12 10:08:48,306 [ 317350]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: Defaulting to no-operation (NOP) logger implementation 
2018-01-12 10:08:48,306 [ 317350]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Enabled plugins**
Database Tools and SQL
Env File
Git Integration
Scala
YAML

### PR DESCRIPTION
**Pull request by savulchik**
Fixes #53.

I did some testing and debugging of the fix in IDEA to make sure the plugin is still working as expected and the original problem with running ScalaTest configuration is resolved.

### CODE REVIEW

File: project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java [hunk 1]
```diff
@@ -50,7 +53,14 @@ protected void validateConfiguration(@NotNull RunConfigurationBase configuration
 
     @Override
     public <T extends RunConfigurationBase> void updateJavaParameters(T configuration, JavaParameters params, RunnerSettings runnerSettings) throws ExecutionException {
-        EnvFileConfigurationEditor.patchEnvironmentVariables(configuration, params.getEnv());
+        Map<String, String> newEnv = new HashMap<>();
```
Comment (ashald) [inline project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java]: This is a common thing that we will have to do in all supported products to it's better to minimize number of actions we perform here. I think it'd be better to do it as:
```
Map<String, String> newEnv = EnvFileConfigurationEditor.patchEnvironmentVariables(configuration, params.getEnv());
params.setEnv(newEnv);
```
so that `EnvFileConfigurationEditor.patchEnvironmentVariables` would be taking care of producing the overall environment variables set but would rather return it as a new map rather than modify an existing one in-place. This would minimize changes as well.

**Review by ashald — COMMENTED** [review]
@savulchik thank you for the pull request! I left a comment on one of the changes so please let me know what you think about that.

Also, it looks like you updated the code for the Idea integration but not for other products. A change like this would affect them as well.

File: project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java (hunk 1 above)
Comment (savulchik) [reply project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java]: Thanks for suggestion, I'll do it. 
As each product provides it's own API for interaction with environment variables the part of updating/replacing them will be different in each extension though.

Comment (ashald) [reply project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java]: There is a common interface that we can rely on - each of them provides access to a `RunConfigurationBase` instance (that we can use to read env files) and a map of environment variables that were set previously. So I don't think that should be an issue.

Comment (savulchik) [reply project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java]: As I found out the actual outlier is the IDEA extension that doesn't call `RunConfigurationExtensionBase#patchCommandLine` that could have been the unified place of updating environment variables.

Please take a look at the new commits I added.

File: project/platform/src/net/ashald/envfile/platform/ui/EnvFileConfigurationEditor.java [hunk 2]
```diff
@@ -104,24 +104,37 @@ public static void writeExternal(@NotNull RunConfigurationBase configuration, @N
...
     }
 
-    public static void patchEnvironmentVariables(@NotNull RunConfigurationBase runConfigurationBase, Map<String, String> environmentVariables) throws ExecutionException {
+    public static void patchEnv(@NotNull RunConfigurationBase runConfigurationBase, Map<String, String> currentEnv) throws ExecutionException {
+        Map<String, String> newEnv = EnvFileConfigurationEditor.collectEnv(runConfigurationBase, currentEnv);
+        currentEnv.clear();
+        currentEnv.putAll(newEnv);
+    }
+
+    public static Map<String, String> collectEnv(@NotNull RunConfigurationBase runConfigurationBase, Map<String, String> userEnv) throws ExecutionException {
```
Comment (ashald) [inline project/platform/src/net/ashald/envfile/platform/ui/EnvFileConfigurationEditor.java]: Let's make `collectEnv` our main interface and drop the `patchEnv` defined above - I'll comment below about how we will use it.

File: project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java [hunk 3]
```diff
@@ -48,9 +50,17 @@ protected void validateConfiguration(@NotNull RunConfigurationBase configuration
...
+     * calls this method instead of RunConfigurationExtensionBase#patchCommandLine method
+     * that we could have used to update environment variables.
+     */
     @Override
     public <T extends RunConfigurationBase> void updateJavaParameters(T configuration, JavaParameters params, RunnerSettings runnerSettings) throws ExecutionException {
-        EnvFileConfigurationEditor.patchEnvironmentVariables(configuration, params.getEnv());
+        Map<String, String> newEnv = EnvFileConfigurationEditor.collectEnv(configuration, params.getEnv());
+        // there is a chance that env is an immutable map,
+        // that is why it is safer to replace it instead of updating it
+        params.setEnv(newEnv);
```
Comment (ashald) [inline project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java:63]: 👍 - we want all other integrations done in similar way - will comment below

File: project/products/pycharm/src/net/ashald/envfile/products/pycharm/PyCharmRunConfigurationExtension.java [hunk 4]
```diff
@@ -50,7 +50,7 @@ protected void validateConfiguration(@NotNull AbstractPythonRunConfiguration con
 
     @Override
     protected void patchCommandLine(@NotNull AbstractPythonRunConfiguration configuration, @Nullable RunnerSettings runnerSettings, @NotNull GeneralCommandLine cmdLine, @NotNull String runnerId) throws ExecutionException {
-        EnvFileConfigurationEditor.patchEnvironmentVariables(configuration, cmdLine.getEnvironment());
+        EnvFileConfigurationEditor.patchEnv(configuration, cmdLine.getEnvironment());
```
Comment (ashald) [inline project/products/pycharm/src/net/ashald/envfile/products/pycharm/PyCharmRunConfigurationExtension.java]: Here and in RubyMine integration below let's do:
```
Map<String, String> cmdEnvironment = cmdLine.getEnvironment();
Map<String, String> newEnv = EnvFileConfigurationEditor.collectEnv(configuration, cmdEnvironment);
cmdEnvironment.clear();
cmdEnvironment.putAll(newEnv);
```

Even though it's more code right away, we're maintaining a pure interface with the plugin core and containing all the specifics of platform integration within respective extension files.

**Review by ashald — CHANGES_REQUESTED** [review]
I think we're almost there - I really like how it's shaping around `collectEnv`.

File: project/products/pycharm/src/net/ashald/envfile/products/pycharm/PyCharmRunConfigurationExtension.java (hunk 4 above)
Comment (savulchik) [reply project/products/pycharm/src/net/ashald/envfile/products/pycharm/PyCharmRunConfigurationExtension.java]: At first I did it exactly that way but in order to get rid of the code duplication I restored the `patchEnv` method. 
I reverted the last commit with the `patchEnv` method:)

File: project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java (hunk 3 above)
Comment (savulchik) [reply project/products/idea/src/net/ashald/envfile/products/idea/IdeaRunConfigurationExtension.java:63]: Done

File: project/platform/src/net/ashald/envfile/platform/ui/EnvFileConfigurationEditor.java (hunk 2 above)
Comment (savulchik) [reply project/platform/src/net/ashald/envfile/platform/ui/EnvFileConfigurationEditor.java]: Done

**Comment by ashald** [comment]
Looks great to me - thanks for the patience and great work!

**Comment by ashald** [comment]
Last thing that I'd like to ask you to do is to add yourself to the list of contributors in `AUTHORS.md`. :)

**Comment by savulchik** [comment]
Thanks for your guidance & positive feedback 👍

**Review by ashald — APPROVED** [review]
